title: Jeanne Goupil # your name (or website title) here
logo: "/Users/jeannegoupil/Library/Mobile Documents/com~apple~CloudDocs/CloudBox/New LOGO LEPS" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Doctorat de sant√© publique 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
